newsletter:
    resource: "@NewsletterBundle/Controller/"
    type:     annotation
    prefix:   /

user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

