events:
    resource: "@EventsBundle/Controller/"
    type:     annotation
    prefix:   /

association:
    resource: "@AssociationBundle/Controller/"
    type:     annotation
    prefix:   /

forum_post:
    resource: "@ForumBundle/Controller/PostController.php"
    type:     annotation

forum_topic:
    resource: "@ForumBundle/Controller/TopicController.php"
    type:     annotation

forum_forum:
    resource: "@ForumBundle/Controller/ForumController.php"
    type:     annotation

article_tags:
    resource: "@ArticleBundle/Controller/TagsController.php"
    type:     annotation

article_article:
    resource: "@ArticleBundle/Controller/ArticleController.php"
    type:     annotation

newsletter:
    resource: "@NewsletterBundle/Controller/"
    type:     annotation

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix:   /
