article_tags:
    resource: "@ArticleBundle/Controller/TagsController.php"
    type:     annotation

article_article:
    resource: "@ArticleBundle/Controller/ArticleController.php"
    type:     annotation

user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

