
article_tags:
    resource: "@ArticleBundle/Controller/TagsController.php"
    type:     annotation

article_article:
    resource: "@ArticleBundle/Controller/ArticleController.php"
    type:     annotation

newsletter:
    resource: "@NewsletterBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

